version: 0.2

phases:
  install: 
    commands:
      - echo installing phase
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the code as docker image
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - imagedefinitions.json