version: 0.2

phases:
  pre_build:
    commands:
      - echo entring the Pre_Build phase...
      - S3_BUCKET=mbay-shoppers-bucket
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build:$ENVIRONMENT
  post_build:
    commands:
      - aws s3 sync ./out/* $S3_BUCKET 
      - echo Build completed on `date`
