version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo entring the Pre_Build phase...
      - S3_BUCKET=mbay-shoppers-bucket
      - apt-get update
      - apt-get install sudo
      - chmod +x ./scripts/install-aws
      - ./scripts/install-aws
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out/* $S3_BUCKET 
      - echo Build completed on `date`
