version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 328246126808.dkr.ecr.eu-west-3.amazonaws.com
      - REPOSITORY_URI=328246126808.dkr.ecr.eu-west-3.amazonaws.com/shoppers
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --platform=linux/amd64 -t shoppers .
      - docker tag shoppers:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"shoppers","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - echo Build completed on `date`
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json