version: 0.2

phases:
  pre_build:
    commands:
      - echo entring the Pre_Build phase...
      - S3_BUCKET=mbay-shoppers-bucket
      - sudo chown -R 99:0 "/root/.npm"
      - npm i node@18.12.0 -g
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - node -v
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./out/* $S3_BUCKET 
      - echo Build completed on `date`
